name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Cache node_modules
      - name: Cache node modules
        uses: actions/cache@v3  # Correct action for caching
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Install dependencies
      - name: Install Dependencies
        run:  |
          npm install
          cd client && npm install

      # Build the project
      - name: Build Angular app
        run: cd client && npm run client-build --prod  # Command to build client

  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Renovate CLI
      - name: Install Renovate
        run: npm install -g renovate

      # Run Renovate to update dependencies
      - name: Update Dependencies
        run: renovate

      # Optionally, commit and push changes made by Renovate
      - name: Commit and Push Changes
        run: |
          git config --global user.name "r0755466"
          git config --global user.email "rayan.azzi98@gmail.com"
          git add .
          git commit -m "Automated dependency updates" || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
